version: '3.1'

services:

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432

  user_service:
    container_name: user_service
    build:
      context: .
      dockerfile: user_service/Dockerfile
    image: user_service:latest
    expose:
      - 9001
    ports:
      - 9001:9001

  user_daemon:
    container_name: user_daemon
    build:
      context: .
      dockerfile: user_daemon/Dockerfile
    image: user_daemon:latest
    expose:
      - 9002
    ports:
      - 9002:9002