version: '3.1'

services:

  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432

  service1:
    container_name: service1
    build:
      context: .
      dockerfile: service1/Dockerfile
    image: service1:latest
    expose:
      - 9001
    ports:
      - 9001:9001

  daemon1:
    container_name: daemon1
    build:
      context: .
      dockerfile: daemon1/Dockerfile
    image: daemon1:latest
    expose:
      - 9002
    ports:
      - 9002:9002